### ISSUE TITLE
An error occured: Index: 14192, Size: 14192

### ISSUE THREAD

**Issue by copyymk** [compomics/denovogui#26]
Hi,

```
i run the software on windows platform with 30G ram, but error:
```

"An error occured: Index: 14192, Size: 14192"

**Comment by hbarsnes** [comment]
Hi,

Thanks for telling us about this. Could you send us the DeNovoGUI log file? You'll find it in via Help > Bug Report.

Best regards,
Harald

**Comment by copyymk** [comment]
Hi,
Tue Apr 19 17:37:42 CST 2016: DeNovoGUI version 1.10.3.

java.lang.IndexOutOfBoundsException: Index: 14192, Size: 14192
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.compomics.util.experiment.io.massspectrometry.MgfIndex.getSpectrumTitle(MgfIndex.java:239)
	at com.compomics.util.experiment.massspectrometry.SpectrumFactory.getSpectrumTitle(SpectrumFactory.java:992)
	at com.compomics.util.experiment.io.identifications.idfilereaders.NovorIdfileReader.getAllSpectrumMatches(NovorIdfileReader.java:276)
	at com.compomics.util.experiment.io.identifications.idfilereaders.NovorIdfileReader.getAllSpectrumMatches(NovorIdfileReader.java:125)
	at com.compomics.denovogui.gui.ResultsFrame.importDeNovoResults(ResultsFrame.java:3283)
	at com.compomics.denovogui.gui.ResultsFrame$51.run(ResultsFrame.java:2723)

Thanks!

**Comment by hbarsnes** [comment]
Hi,

Thanks for the log file. It seems like DeNovoGUI is trying to read the final spectrum in your mgf file but fails to do so due to an index issue with the file (the first spectrum is at index 0). Not really sure how this can happen. Could it be that your mgf file contains both MS1 and MS2 spectra? As MS1 spectra are ignored by Novor which would mess up the mgf index?

Best regards,
Harald

**Comment by copyymk** [comment]
Thanks! I used the new mgf file to instand of the old one and it work. Thanks again!

**Comment by hbarsnes** [comment]
Great! It would be great if you could send me the original mgf file so that perhaps we can try to find a way around it even for the original file?
